# Generated by Django 5.0.6 on 2024-06-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_workdesk_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdesk',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='workdesk',
            name='title',
        ),
    ]
