# Generated by Django 5.0.6 on 2024-06-23 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_workdesk_parent_remove_workdesk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdesk',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.workdesk'),
        ),
        migrations.AddField(
            model_name='workdesk',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
