# Generated by Django 5.0.6 on 2024-06-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_workdesk_parent_remove_workdesk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_desk',
            field=models.ManyToManyField(to='account.workdesk'),
        ),
    ]
