# Generated by Django 5.0.6 on 2024-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_desk',
            field=models.ManyToManyField(null=True, to='account.workdesk'),
        ),
    ]
