# Generated by Django 5.0.6 on 2024-06-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('status', models.CharField(choices=[('I', 'Inativo'), ('A', 'Ativo'), ('P', 'Pendente')], default='I', max_length=1)),
                ('telephone', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
