# Generated by Django 5.0.6 on 2024-07-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='parent',
            new_name='sub_id',
        ),
    ]
