# Generated by Django 5.0.6 on 2024-06-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_workdesk'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ticket.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
                ('creation_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('ticket_type', models.CharField(choices=[('A', 'Incidente'), ('B', 'Problema'), ('C', 'Requisição')], default='A', max_length=2)),
                ('priority', models.CharField(choices=[('A', 'Baixa'), ('B', 'Media'), ('C', 'Alta'), ('D', 'Urgente')], default='A', max_length=2)),
                ('status', models.CharField(choices=[('A', 'Atrasado'), ('B', 'Em Andamento'), ('C', 'Em Espera'), ('D', 'Concluido')], default='B', max_length=2)),
                ('category', models.ManyToManyField(to='ticket.category')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients')),
                ('work_desk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.workdesk')),
            ],
        ),
    ]
