# Generated by Django 5.0.6 on 2024-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='Descrição'),
        ),
    ]
