# Generated by Django 5.0.6 on 2024-06-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticketlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='type',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='log_type',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='modified_field',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticket_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
