# Generated by Django 5.0.6 on 2024-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_rename_id_user_ticketlog_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='datetime_log',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
