# Generated by Django 5.0.6 on 2024-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_ticketlog_datetime_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
