# Generated by Django 5.0.6 on 2024-06-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_testedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
