# Generated by Django 5.0.6 on 2024-06-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_remove_ticket_sla_sla_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.sla'),
        ),
    ]
