# Generated by Django 5.0.6 on 2024-07-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_remove_ticket_sla_sla_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.sla'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='status',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
