# Generated by Django 5.0.6 on 2024-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_ticket_sla_alter_sla_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sla',
        ),
        migrations.AlterField(
            model_name='sla',
            name='status',
            field=models.CharField(choices=[('A', 'Em Espera'), ('B', 'Atendendo'), ('C', 'Pausado'), ('D', 'Concluido')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
